@startuml championnat_ski

class Epreuves{
    - id: int
    - lieu: string
    - date: date

    + créerEpreuve()
    + modifierEpreuve()
    + supprimerEpreuve()

    + démarrerEpreuve()
    + terminerEpreuve()
}

class ListeParticipants{
    - id: int
    - liste_participant: array

    + ajouterListeParticipants()
    + modifierListeParticipants()
}

class Participants{
    - id: int
    - nom: string
    - prénom: string
    - date_de_naissance: date
    - adresse_mail: string
    - photo: string

    + créerParticipant()
    + modifierParticipant()
    + supprimerParticipant()

}

class Passages{
    - id: int
    - numero_passage: int
    - temps_passage: time

}

class Résultats{
    - id: int
    - temps_moyenne: time

    + importerFeuilleChronométrage()
    + exporterFeuilleChronométrage()

    + calculerRésultat()
    + afficherRésultat()
}

abstract class Groupes{
    - id: int
    - nom: string

    + créerGroupe()
    + modifierGroupe()
    + supprimerGroupe()
}

class Catégories{
    - id: int
    - nom: string

    + créerCatégorie()
    + modifierCatégorie()
    + supprimerCatégorie()
}

class Profils{
    - id: int
    - nom: string
    
    + créerProfil()
    + modifierProfil()
    + supprimerProfil()
}

interface modifiable
{
    + créer()
    + modifier()
    + supprimer()
}


Epreuves .right.|> modifiable
Participants ..|> modifiable
Groupes .left.|> modifiable

Groupes <|-- Catégories
Groupes <|-- Profils

Epreuves *-right- ListeParticipants
ListeParticipants -left-o Participants

ListeParticipants *-left- Passages
Passages *-right- Résultats
Epreuves -- Résultats
ListeParticipants -- Résultats
Participants --* Profils
Participants --* Catégories

 
@enduml
